apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: main-2023-04-05-v0.1.2-366-g2761e0f
  name: observatorium-xyz-observatorium-api
  namespace: observatorium
spec:
  ports:
  - appProtocol: h2c
    name: grpc-public
    port: 8090
    targetPort: 8090
  - appProtocol: http
    name: internal
    port: 8081
    targetPort: 8081
  - appProtocol: http
    name: public
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/part-of: observatorium
