apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: main-2023-04-05-v0.1.2-366-g2761e0f
  name: observatorium-xyz-observatorium-api
  namespace: observatorium
